#!/usr/bin/env python3
import subprocess
import argparse
from pathlib import Path

SCRIPTDIR = Path(__file__).parent.absolute()
PASIFICDIR = SCRIPTDIR.parent / "binshare/pasific"

MODEL = PASIFICDIR / "rf13-3.RData"
RFPREDICTION = PASIFICDIR / "RFprediction.R"
STRUCTUREPREDICTION = PASIFICDIR / "structure_prediction.pl"


def parseargs():
    parser = argparse.ArgumentParser()
    parser.add_argument("tmpdir")
    parser.add_argument("filename")
    parser.add_argument("-p", "--p1", action="store_true")
    parser.add_argument("--simple-at", dest="simpleat", action="store_true")
    parser.add_argument("--limit-at", dest="limitat", action="store_true")
    return parser.parse_args()


def main():
    args = parseargs()
    tmpdir = Path(args.tmpdir).absolute()

    p1flag = str(int(args.p1))
    simpleat = str(int(args.simpleat))
    limitat = str(int(args.limitat))

    subprocess.check_output(
        [STRUCTUREPREDICTION, args.tmpdir, args.filename, p1flag, simpleat, limitat]
    )

    outfile = args.filename + ".out"
    outfile_absolute = tmpdir.absolute() / outfile
    print(outfile_absolute)

    subprocess.check_output([RFPREDICTION, MODEL, outfile_absolute])


if __name__ == "__main__":
    main()
